package com.example.KodemiLabs.Model;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;
import java.time.Instant;


@DynamoDBTable(tableName = "LoginHistory")
@AllArgsConstructor
@NoArgsConstructor
@Setter
@DynamoDbBean
public class LoginHistory {

    private String userId;

    private Instant loginAttemptTime;
    private String loginStatus;
    private String ipAddress;
    private String userAgent;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("user_id")
    public String getUserId() {
        return userId;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("login_attempt_time")
    public Instant getLoginAttemptTime() {
        return loginAttemptTime;
    }


    @DynamoDbAttribute("login_status")
    public String getLoginStatus() {
        return loginStatus;
    }


    @DynamoDbAttribute("ip_address")
    public String getIpAddress() {
        return ipAddress;
    }


    @DynamoDbAttribute("user_agent")
    public String getUserAgent() {
        return userAgent;
    }

}

